language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create user helplineuser with password 'helplinepasswd';"
  - psql -U postgres -c "alter role helplineuser superuser;"
before_install:
  - sudo apt install python-dev
  - sudo apt install gettext
  - sudo apt install python-gdal
  - sudo apt install libmemcached-dev
  - sudo apt-get install libz-dev
  - sudo apt-get install language-pack-es

# command to run tests
script:
  - python manage.py test
